import { ProductType } from '../store/AuthSlice';
import { v4 as uuidv4 } from 'uuid';

export const defaultProducts: ProductType[] = [
  {
    id: uuidv4(),
    food_name: 'cheese',
    nf_protein: 25,
    nf_total_fat: 17.2,
    nf_total_carbohydrate: 0,
    nf_calories: 254.8,
    isDefault: true,
    weight: 100,
  },
  {
    id: uuidv4(),
    food_name: 'egg',
    nf_protein: 12.8,
    nf_total_fat: 11.6,
    nf_total_carbohydrate: 0.3,
    nf_calories: 140,
    isDefault: true,
    weight: 100,
  },
  {
    id: uuidv4(),
    food_name: 'tomato',
    nf_protein: 1.1,
    nf_total_fat: 0.2,
    nf_total_carbohydrate: 3.8,
    nf_calories: 24,
    isDefault: true,
    weight: 100,
  },
  {
    id: uuidv4(),
    food_name: 'persimmon',
    nf_protein: 0.5,
    nf_total_fat: 0.4,
    nf_total_carbohydrate: 15.3,
    nf_calories: 67,
    isDefault: true,
    weight: 100,
  },
  {
    id: uuidv4(),
    food_name: 'prunes',
    nf_protein: 1.6,
    nf_total_fat: 0.4,
    nf_total_carbohydrate: 55.4,
    nf_calories: 229,
    isDefault: true,
    weight: 100,
  },
];
